title: OwlArch

description: >- # this means to ignore newlines until "baseurl:"
  The place where OwlArch is generated and maintained.
domain: "leku2020.github.io"
baseurl: "OwlArchSoftware/" # the subpath of your site, e.g. /blog
url: "https://leku2020.github.io/OwlArchSoftware/"
github_username: Leku2020

# Build settings
remote_theme: pages-themes/merlot@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme
 